accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld


def hello_world(request):

    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    # reverse_lazy는 클래스형 뷰에서 사용함
    # 작성이 성공했을 때 연동할 url
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name ='accountapp/detail.html'

class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    # reverse_lazy는 클래스형 뷰에서 사용함
    # 작성이 성공했을 때 연동할 url
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="max-width: 500px; margin: 4rem auto;">

        <div class="mb-4">
            Sign up
        </div>

        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="max-width: 500px; margin: 4rem auto;">

        <div class="mb-4">
            Quit
        </div>

        <form action="{% url 'accountapp:delete' pk=user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-3 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div>
            <p>
                {{ target_user.date_joined }}
            </p>

            <h2>
                {{ target_user.username }}
            </h2>

            {% if target_user == user %}
            <a href ="{% url 'accountapp:update' pk=user.pk%}">
                <p>
                    Change Info
                </p>
            </a>

             <a href ="{% url 'accountapp:delete' pk=user.pk%}">
                <p>
                    Quit
                </p>
            </a>

            {% endif %}

        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}
    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 class="pinterest_logo">Hello World List</h1>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>

            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>

        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}

            <h3>
                {{ hello_world.text }}
            </h3>

            {% endfor %}

        {% endif %}


    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>

        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
            </form>
        </div>

    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="max-width: 500px; margin: 4rem auto;">

        <div class="mb-4">
            Change Info
        </div>

        <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
        </form>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumMyeongjo';">

    {% include 'header.html' %}
    <hr>

    {% block content %}
    {% endblock %}

    <hr>
    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="pinterest_footer">
    <div class="pinterest_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>

    <div style="margin-top:1rem;">
        <h6 class="pinterest_logo">Pinterest</h6>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Ted Pinterest</title>

    <!--부트스트랩 링크-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!--구글 폰트 링크-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <!--css 불러오기-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumMyeongjo';
            src: local('NanumMyeongjo'),
            url("{% static 'fonts/NanumMyeongjo.otf' %}") format("opentype");

         @font-face {
            font-family: 'NanumMyeongjoBold';
            src: local('NanumMyeongjoBold'),
            url("{% static 'fonts/NanumMyeongjoBold' %}") format("opentype");

        @font-face {
            font-family: 'NanumMyeongjoExtraBold';
            src: local('NanumMyeongjoExtraBold'),
            url("{% static 'fonts/NanumMyeongjoExtraBold' %}") format("opentype");

    </style>

</head>

templates/header.html
<div class="pinterest_header">

    <div>
        <h1 class="pinterest_logo">Pinterest</h1>
    </div>

    <div>
        {% if not user.is_authenticated %}
        <!-- next 구문을 get 방식으로 넘겨주면 현재의 request에서 받은 path를 유지하며 로그인 이후 페이지를 불러올 수 있음 -->
        <a href="{% url 'accountapp:login' %}">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}">
            <span>signup</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>my page</span>
        </a>

        <a href="{% url 'accountapp:logout' %}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>

</div>